### ISSUE TITLE
Make sure the reverse iterator of TiKV be available

### ISSUE THREAD

**Issue by shafreeck** [distributedio/titan#123]
Some commands of Redis like `zrevrange`, `rpop`, `random` depends closely on the reverse iterator feature of TiKV.

Make sure it be available as soon as possible.

related pr: https://github.com/pingcap/tidb/pull/9564

**Comment by arthurkiller** [comment]
I will update this PR this week

**Comment by arthurkiller** [comment]
closed via https://github.com/pingcap/tidb/pull/10152
