### ISSUE TITLE
性能测试

### ISSUE THREAD

**Issue by mysunnyshine** [distributedio/titan#147]
我搭了个单机环境，进行测试，但是性能远不如预期。我测试的单机环境如下：
一个 Titan, 一个 Pd， 三个 Tikv ，部署在同一台机器上。用Redis的 bench-mark(Redis 自带的bench-mark, 修改了ip和端口，指向 titan) 测试。求教 是我搭的环境有问题？ 还是别的原因。

测试结果：
![image](https://user-images.githubusercontent.com/24480430/64687574-57e45500-d4bd-11e9-8dbc-b591917001c3.png)

**Comment by arthurkiller** [comment]
性能测试结果要求的机器参数和部署方式如下
https://github.com/distributedio/titan/blob/master/docs/benchmark/benchmark.md

@mysunnyshine

**Comment by arthurkiller** [comment]
要说明的一点是，tikv 底层是基于磁盘存储（rocksdb），对于硬件要求较高。因此测试结果根据部署的物理机配置不同，差距会很大。

**Comment by mysunnyshine** [comment]
> 性能测试结果要求的机器参数和部署方式如下
> https://github.com/distributedio/titan/blob/master/docs/benchmark/benchmark.md
> 
> @mysunnyshine

ok  qqq
