### ISSUE TITLE
如何将 Titan 和 多个Pd 配置在一起

### ISSUE THREAD

**Issue by mysunnyshine** [distributedio/titan#148]
在官方的 benchmark 中， 在两台机器上启动了 Titan 实例，但是 pd 有三个 实例。那么怎么去配置 Titan ，让 一个 Titan 可以和多个 pd 通信？ 
titan.toml里，只看到了 pd-adrs ，但是这个 只能配置一个 pd 的地址。想问下， 官方是怎么配置的？
（英语写能力不够，见谅）

**Comment by nioshield** [comment]
官方配置使用下边的格式
tikv://etcd-node1:port,etcd-node2:port,etcd-node3:port
多个pd 实例地址通过, 分割
