### ISSUE TITLE
titan 并发控制疑问

### ISSUE THREAD

**Issue by zhenyuxie** [distributedio/titan#150]
最近测试 titan 性能，部署了 3 个节点的 tikv 集群，单独部署 titan，然后压测时发现，相同的数据，每个节点平均 30+ region 时，GET qps 大概 7w。调整 region 数后，每个 节点的 region 为1300+个，再次用同样的命令压测，GET qps 能达到 13w，请问 titan 是否有根据 region 数做并发控制呢？

**Comment by shafreeck** [comment]
Titan 并不会根据 Region 数做并发控制，但底层的 TiKV 并发跟 Region 有关。每个 Region 是一个 Raft Group，并发会受到 Raft 处理性能的影响。Region 数变多，并发效果也会变好。另外，Region 数变多受，系统数据的分布可能会更均衡，这样节点的资源利用率可能比较高，也会增加并发性能。

但并不是 Region 数越多越好，当 Region 较多，集群心跳也会增多，占用网络，另外 PD 管理 Region 的代价也会变大。当然，你现在的规模 Region 并不算多。目前支持上百万 Region 没有问题。

**Comment by zhenyuxie** [comment]
region 调整前后负载都是均匀的，所以排除 region 数增多使得负载均衡的点。所以最大的可能性是 tikv 内部有按照 region 维度来控制并发，但是不知道 tikv 底层是如何做的并发控制。昨天咨询 tikv 的同学，他们给的答案是 region 内部并不会对并发做控制，所以感觉比较疑惑。

**Comment by zhenyuxie** [comment]
请教下，region 内部是串行处理所有请求的吗？如果是这样，那 region 数越多并发效果应该会更好。

**Comment by zhenyuxie** [comment]
> Titan 并不会根据 Region 数做并发控制，但底层的 TiKV 并发跟 Region 有关。每个 Region 是一个 Raft Group，并发会受到 Raft 处理性能的影响。Region 数变多，并发效果也会变好。另外，Region 数变多受，系统数据的分布可能会更均衡，这样节点的资源利用率可能比较高，也会增加并发性能。
> 
> 但并不是 Region 数越多越好，当 Region 较多，集群心跳也会增多，占用网络，另外 PD 管理 Region 的代价也会变大。当然，你现在的规模 Region 并不算多。目前支持上百万 Region 没有问题。

测试使用的是单副本，region 调整前后负载都是均匀的，所以排除 region 数增多使得负载均衡的点。所以最大的可能性是 tikv 内部有按照 region 维度来控制并发，但是不知道 tikv 底层是如何做的并发控制。昨天咨询 tikv 的同学，他们给的答案是 region 内部并不会对并发做控制，所以感觉比较疑惑。
如果 region 内部是串行处理所有请求的吗？如果是这样，那 region 数越多并发效果应该会更好。
