### ISSUE TITLE
hset的qps大概是多少？

### ISSUE THREAD

**Issue by mineralres** [distributedio/titan#156]
我用docker简单部署了一个测试环境, 一个tikv,  一个pd, 一个titan， 8核心8G内存，做了hset的测试，key有16字节，value大概是180字节，一个连接使用pipeline一次性发送到服务器，测试结果只有 25~35 的qps，不知道这个结果是我自己问题，还是本来就是这么慢?
hvals响应很快，我查询一个大概5000个key的hash，粗略一看响应在<500ms。

**Comment by YIDWang** [comment]
你好 ，tikv 存储推荐使用ssd 。在您的描述中没有提到磁盘。如果使用机械磁盘，这个性能是可以接受的。

发自我的iPhone

**Comment by mineralres** [comment]
谢谢！明白了，我确实是用机械磁盘测试的。
