### ISSUE TITLE
在不改动tikv代码的前提下，sorted set接口是否难以完整支持？

### ISSUE THREAD

**Issue by mars00772** [distributedio/titan#157]
看到诸如zincrby等最重要的接口仍未实现。

**Comment by shafreeck** [comment]
目前不好支持的主要是反向遍历相关的操作。zincrby 是很容易支持的，只是提供 zset 实现的同学可能没这个需求，就没有实现，如果你有兴趣的话，可以给我们提 PR。

另外，这种incr 类的命令，并发会导致比较严重的事务冲突，性能会比较低，也不太建议使用。
