### ISSUE TITLE
是否考虑使用rawkv实现redis，事务接口比较影响性能

### ISSUE THREAD

**Issue by jacky1193610322** [distributedio/titan#186]
1. 事务接口除了获取TSO消耗性能，还有就是目前tikv乐观锁的设计造成自增incr这种命令可能会出现很多重试
2. 使用rawkv实现的话，如果是分布式处理的话会造成同一个key的并发问题，为了解决这个问题，可以让每个key固定在每个proxy上，也就是使用hash的方式来拆分key空间，这样虽然proxy是有状态的，但是这个状态很轻，因为他不存储数据，只存储一个映射，类似于codis的proxy，可以接受。
3. 就是针对redis本来的设计，不需要事务来保证什么， 每个命令都是独立的

**Comment by shafreeck** [comment]
1. incr 命令如果使用 rawkv 的话，也是需要先读取再更新，因为 tikv 没有提供原生 incr 命令，因此我们实现的时候，需要引入分布式锁。
2. hash 来拆分 key 空间，在新增节点或挂掉节点时，会造成 hash 路由的失效
3. 针对 redis 的设计，天然需要事务来保证。对于 list， hash， set 等类型，因为其原信息（比如长度，类型等）需要持久化，也就是说，数据和原信息必须原子性提交。

**Comment by jacky1193610322** [comment]
> 1. incr 命令如果使用 rawkv 的话，也是需要先读取再更新，因为 tikv 没有提供原生 incr 命令，因此我们实现的时候，需要引入分布式锁。
> 2. hash 来拆分 key 空间，在新增节点或挂掉节点时，会造成 hash 路由的失效
> 3. 针对 redis 的设计，天然需要事务来保证。对于 list， hash， set 等类型，因为其原信息（比如长度，类型等）需要持久化，也就是说，数据和原信息必须原子性提交。

1. 第一个问题 针对incr 如果允许多台更新的话，是需要并发控制，但是上面说了，会使用hash slot的方式，所以每个key只会落在一台proxy上面，那么就不存在并发更新，也不需要引入分布式锁。
2. 新增节点和挂掉节点，hash路由失效，这不影响，失效我就让路由落在活着的机器上面，这时候有可能存在双主的情况，可以使用租约锁的方式，类似于这个连接[这里](http://www.52im.net/thread-1999-1-1.html) 租约锁的方式。因为是轻量级状态，这个状态的修改会非常快，针对正常关机等，可以优化立即释放租约锁，这个时间跟机器宕机命令重试时间 差别不大。
3. 针对部分需要事务的就使用事务，但是目前是所有命令都使用事务。

**Comment by shafreeck** [comment]
第 1  点的正确性，依赖于第 2 点的正确性保证。关于第 2 点，能否具体阐述下，租约锁是如何保证路由的正确性的？如果存在双主的情况，并发写的正确性又是如何保证的呢？

关于第 3 点， TiKV 是不支持 RawKV 和 TxnKV 的 API 混用的，不只数据无法读取，还可能导致访问请求因为数据格式不对而失败。至于数据修复的方式，有实现复杂度和性能两个主要方面的考虑，最主要还是性能方面的考虑。我们也尝试用类似先写数据，不更新元信息，而是等具体读取数据的时候修复元信息的方式来减少事务冲突，但其带来的性能代价可能难以接受（比如扫描一个大 list 来计算长度）

**Comment by jacky1193610322** [comment]
第二点， 假设把key空间按照1024来hash分成1024个slot，每个slot会分配到一台proxy机器上，由这个机器负责这个slot的所有操作，每个proxy 需要跟另外一个组件包，来维持租约不管是etcd还是一个单独的服务都可以，假设当前是一切都正常状态，现在要重启机器，或者一台机器意外宕机，需要保证这个slot转移到别的机器上负责，这个服务称为metaserver，那么当检测到这个机器心跳不正常之后，那么将slot重新分配到存活的机器上，其他机器加载这个slot，但是不能立即生效，需要等到一个租约锁的时间，才能生效，失去心跳的proxy，立即停止其上面slot的读写，告知client重新拉取路由信息，这样可以避免双主的产生，但同时会带来一小会服务不可用，但是如果是正常关机，可以告知metaserver，允许重新分配的机器立即加载使用，只有异常宕机的情况下才会有一小会不可用时间。

**Comment by shafreeck** [comment]
我相信使用 Hash 路由的方案是一定能做到的，但实际要比上述的方案要复杂。

上述租约锁的机制并不严谨，这本质上是一个路由信息一致性的问题，可以抽象为：1. 挂掉节点停止读写， 2. 新分配 slot 节点开始服务 这两个步骤的顺序问题。也就是解决在分布式环境下1， 2 顺序执行的问题，本质上，可以将 1， 2 两个操作当成一个事务来对待。

## 其正确性需要有如下保证：
### 1. 原子性
两个操作必须同时成功，如果 1 失败， 2 成功，则产生双主问题， 如果 1 成功， 2 失败，则导致不可用。

我们排除代码 BUG 的问题，也就是操作 1 不会因为 BUG 而失败。那么，操作 1 本质上是一个无时间上限（time upper bound）的异步操作：在不确定的时间内停止读写。比如：节点 hang 住时间超过 N 秒，节点在 N 秒之后仍然可能有读写操作。另外，我们不能为“停止读写” 这个操作设定超时，因为超时意味着不确定的结果，可能导致双主。也就是说，就算没有代码 BUG，也可能存在1 失败， 2 成功的问题。

第二种情况， 1 成功停止了读写， 执行 2 步骤时，可能新节点挂掉，拉取路由超时（可以重试）等问题，我们可以实现 2 的最终成功，但其中的不可用时间实际要比理想情况下要长。

### 2. 顺序一致性
即1 必须在 2 之前执行成功

在上面已经描述，步骤 1 可能因为节点hang住而导致“停止读写” 操作的延迟执行，当节点恢复的时候，必然有些读写操作会继续发送给存储节点。 这时候新的 slot 节点其实已经启用，导致双主的并发写。

租约锁的机制本质上用到了两种技术：
#### 租约（心跳）
这里本质上是做故障监测，故障监测有两方面需要考虑：完整性，和准确性。完整性是指有多少监测节点认为该节点故障。准确性是指判断该节点故障是否是正确的。我们假设使用 etcd 的租约机制，本质上就是 etcd 的主节点对该节点做故障监测，因为只有一个参与节点，我们可以不考虑完整性的问题。那么剩下的就是准确性问题，两个方面导致影响了监测的准确性：
1. 不精确的时钟：租约是依赖心跳与时钟的，如果时钟不准确，会导致监测结果不准确。当然， 这个可以用 PD 的全局始终来解决。
2. 操作异步性：所谓异步，是指某个操作没有时间上限，比如被监测节点被 hang 住的情况，导致被监测节点没有及时停止读写。

综上来看，租约对故障监测的准确性，是最终一致的。也就是最终被认为挂掉的节点，会停止读写，但时间可能超过设定的 N。

#### 提交等待（Commit wait，见 Spanner 论文）
如果故障监测是准确的， 那么路由信息等待时间 N 后生效（提交等待）就是正确的。但基于上述分析，这点是保证不了的。

## 解决方案
引入版本

我们可以思考，为什么 raft 基于租约可以选主，为什么 Spanner 提交等待可以实现，这是因为除了上述安全保证外，还需要版本信息做顺序保证。在 raft 选主中，是 term 避免了旧 leader hang住恢复后的读写行为。在 spanner 中，是 version 保证了新的写不跟旧的写入冲突。

引入版本，至少意味着引入单行事务。RocksDB 可以保证单行事务，但 TiKV 只暴露出了扁平化 KeyValue，我们想要保证正确，则需要自己实现 MVCC 及单行事务（比如 CAS），但绕这么多弯，实际上的开发代价和性能代价，可能已经超过使用事务接口。

## 总结
TiKV 是一个严谨的分布式存储，其从原理上就保证了数据的正确性，一致性，其 ACID 是可以形式化证明的。我们基于上层的封装如果破坏了这种正确性，使用一种不够严谨规范的解决方案解决部分问题，我觉得是得不偿失的。我个人整体的思路，更倾向是使用事务接口，保证正确性易用性，通过优化实现来提升性能（比如 1PC， 减少 TSO 获取等）

**Comment by jacky1193610322** [comment]
谢谢作者精彩的回复，目前看rawkv实现，如果要实现meta与data的一致性，本身就是要实现一套事务，也就是tikv已经做的。目前这边考虑不使用tikv作为底层存储。类似于pika 在单机来保证meta和data信息的一致性。

上面方案正确性的前提就是N时间内，原有的proxy一定把自己隔离了。 这个我认为是个取舍，比如STW等等都会造成机器并没有实际隔离，但是我认为这是个折中。比如我认为异常宕机N设置为10秒，有最大10秒不可用时间。
如果严格要解决解决双主，我认为:
1. 需要底层存储支持fence(底层不会允许连个leader同时写同一个slot)。
2. 能够执行物理隔离或者IO隔离(比如ssh 登录强杀，如果失败 那就人工接入)。
3. 避免双主的方案。

**Comment by shafreeck** [comment]
@jacky1193610322 Pika 及类似的系统确实是一中解决方案，并且在数据规模不是特别大的时候（比如 10T），也是比较节省成本的解决方案。据我了解，在美图和转转都有过使用 Pika 的尝试，不过最后也都放弃了，可能是在使用过程中也遇到一些坑（确切不太了解）。

Titan 的话，主要是考虑成本问题，对于大规模数据量更合适一点。性能上的话，简单的 KV 访问都是小于 10ms 的， QPS 可以通过加节点水平扩展。 本身性能上的话，更多的是依赖 TiKV 的性能优化， 鉴于 TiKV 项目目前发展良好，性能优化也在持续进行，这对 Titan 来说本身就是一种红利（可能什么都不用做，性能就提高很多）。

很高兴能一起讨论这个问题，我们对这个问题的认识也更加清晰了。

**Comment by jacky1193610322** [comment]
谢谢作者回复，会持续关注
