### ISSUE TITLE
Support for Raw KV Client

### ISSUE THREAD

**Issue by scriptnull** [distributedio/titan#187]
Currently titan is trying to communicate with TiKV using its Transactional KV API. I would like to know if there is a way to use Raw KV API instead. If not, I wonder if this issue could be considered as feature request.

**Comment by arthurkiller** [comment]
dumplicated #186

**Comment by arthurkiller** [comment]
Can you translate Chinese into English via google translate? If not, we can talk about this here. Both of you have the same querstion. : )

**Comment by shafreeck** [comment]
We have discussed this a lot, there is no ideal way to implement Titan using the RawKV API. You can share your ideas if you have some.
