### ISSUE TITLE
titan监控问题

### ISSUE THREAD

**Issue by hugo2007** [distributedio/titan#188]
请问titan的监控数据从哪里可以获取？
在http://xxx:7345/metrics 这个接口获取的数据表示看不懂。谢谢！

**Comment by arthurkiller** [comment]
这个是prometheus格式监控数据。
可以使用prometheus采集后使用grafana进行展示，我记得还上传过grafana的模板

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
Sent from my iPhone

**Comment by hugo2007** [comment]
> 这个是prometheus格式监控数据。 可以使用prometheus采集后使用grafana进行展示，我记得还上传过grafana的模板 Have an awesome day ✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️ Arthur lee Sent from my iPhone
> […](#)
> 在 2020年2月16日，下午1:33，hugo2007 ***@***.***> 写道： ﻿ 请问titan的监控数据从哪里可以获取？ 在http://xxx:7345/metrics 这个接口获取的数据表示看不懂。谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，请问titan监控的grafana的模板在哪个目录下呢？我没找到。

**Comment by arthurkiller** [comment]
好像忘了上传 = =||| ，等明儿的吧，看下怎么把配置发过去。

**Comment by hugo2007** [comment]
> 好像忘了上传 = =||| ，等明儿的吧，看下怎么把配置发过去。

嗯嗯，麻烦上传一下。我们线上打算使用titan，现在发现缺少了qps，时延，失败率等基础监控。
顺便问下，titan有在其他公司上线使用么？我看git上面的记录现在最新release是0.6.0版本。

**Comment by YIDWang** [comment]
你可以加一下微信群，我们可以在微信群里讨论。配置可以先行私法你。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hugo2007"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月17日(星期一) 中午11:06
收件人:&nbsp;"distributedio/titan"<titan@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [distributedio/titan] titan监控问题 (#188)



 
好像忘了上传 = =||| ，等明儿的吧，看下怎么把配置发过去。
  
嗯嗯，麻烦上传一下。我们线上打算使用titan，现在发现缺少了qps，时延，失败率等基础监控。
 顺便问下，titan有在其他公司上线使用么？我看git上面的记录现在最新release是0.6.0版本。

**Comment by hugo2007** [comment]
请问微信群的号码是多少呢？我加一下。

**Comment by YIDWang** [comment]
vx：1520990951 我拉你进群吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hugo2007"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 中午11:16
收件人: "distributedio/titan"<titan@noreply.github.com&gt;; 
抄送: "yid"<1520990951@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [distributedio/titan] titan监控问题 (#188)




请问微信群的号码是多少呢？我加一下。
