### ISSUE TITLE
rpop command bug

### ISSUE THREAD

**Issue by dingyiran** [distributedio/titan#199]
Maybe rpop command implement bug ?

10.1.1.1:7369> RPUSH mylist "one"
(integer) 1
10.1.1.1:7369> RPUSH mylist "two"
(integer) 2
10.1.1.17369> RPUSH mylist "three"
(integer) 3
10.1.1.1:7369> RPOP mylist
"two"
10.1.1.1:7369> LRANGE mylist 0 -1
1) "one"
2) "three"

Not pop the right one

**Comment by arthurkiller** [comment]
[need investigetion]
seems this tiDB(sdk) has bug during seek the key in reverse mode.

**Comment by dingyiran** [comment]
Bug is already resolved。Thanks
