### ISSUE TITLE
The bug about query pre key use scan.  error msg: strconv.ParseUint: parsing "fil:test2:key:0": invalid syntax

### ISSUE THREAD

**Issue by liweilijie** [distributedio/titan#213]
package main

import (
        "fmt"
        "github.com/go-redis/redis"
        "strconv"
)

func main() {
        client := redis.NewClient(&redis.Options{
            Addr:     "127.0.0.1:7369",
                Password: "xxx", // no password set
                DB:       0,  // use default DB
        })

        for i := 0; i < 106; i++ {
            client.Set("fil:test2:key:"+strconv.Itoa(i), "value"+strconv.Itoa(i), 0)
        }

        var cursor uint64
        var n int
        for {
                var keys []string
                var err error
             
                keys, cursor, err = client.Scan(cursor, "*", 20).Result()
                if err != nil {
                        panic(err)
                }
                n += len(keys)

                fmt.Printf("\nfound %d keys\n", n)
                var value string
                for _, key := range keys {
                        value, err = client.Get(key).Result()
                        fmt.Printf("%v %v\n", key, value)
                }
                if cursor == 0 {
                        break
                }
        }
    }

**Comment by nioshield** [comment]
The cursor is returned as Bulk Strings. titan and redis-server are the same, but the implementation is different. titan returns the next key as cursor
The panic is go-redis converts curosr as uint64, so you can try using other Redis Client libraries, for example:
```go
package main
import (
    "fmt"
    "strconv"
    "github.com/gomodule/redigo/redis"
)
func main() {
    c, _ := redis.Dial("tcp", "ip:port")
    defer c.Close()
    for i := 0; i < 106; i++ {
        c.Do("SET", "fil:test2:key:"+strconv.Itoa(i), "value"+strconv.Itoa(i))
    }
    cursor := []byte("0")
    var n int
    for {
        var keys []string
        vals, err := redis.Values(c.Do("SCAN", cursor, "*", 20))
        if err != nil {
            panic(err)
        }
        redis.Scan(vals, &cursor, &keys)
        n += len(keys)
        fmt.Printf("\nfound %d keys and cursor %s\n", n, cursor)
        var value string
        for _, key := range keys {
            value, err = redis.String(c.Do("GET", key))
            fmt.Printf("%s %s\n", key, value)
        }
        if string(cursor) == "0" {
            break
        }
    }
}
```

**Comment by liweilijie** [comment]
3q
