### ISSUE TITLE
List lrem、ltrim unknown command

### ISSUE THREAD

**Issue by kisszhangxiansen** [distributedio/titan#215]
org.springframework.dao.InvalidDataAccessApiUsageException: unknown command 'lrem'; nested exception is redis.clients.jedis.exceptions.JedisDataException: unknown command 'lrem'
我看文档说 titan 支持list命令列表里有着两个命令 但是我本地部署测试报错，想知道是我用错了吗

**Comment by nioshield** [comment]
这两个命令应该是还没有支持,文档可能存在误差
