### ISSUE TITLE
有计划支持 blpop brpop brpoplpush zremrangebyrank zremrangebyscore吗

### ISSUE THREAD

**Issue by alexKeleon** [distributedio/titan#225]
blpop brpop   这个阻塞式的pop  tikv的原语应该不支持？只能在titan 客户端里模拟？

**Comment by arthurkiller** [comment]
@alexKeleon 是的，tikv 没有类似的机制可以用来实现 block operation

**Comment by arthurkiller** [comment]
换个角度来看，`block` 其实算是一种通知的元语，用于通知用户某个事件发生了（例如：某个 key 可写、可读）。
因此可能从更通用的角度来看， `pub/sub` 的优先级会更高一点。

**Comment by arthurkiller** [comment]
@alexKeleon 你们对于使用 titan 有任何想交流和体验的也可以加微信群沟通~欢迎提出你们的想法和遇到的问题

**Comment by alexKeleon** [comment]
> @alexKeleon 你们对于使用 titan 有任何想交流和体验的也可以加微信群沟通~欢迎提出你们的想法和遇到的问题

微信群怎么加

**Comment by arthurkiller** [comment]
你可以加我微信😄
![image](https://user-images.githubusercontent.com/11133870/126116622-72107afa-4691-4bd0-9031-7aa09e6ab74f.png)

**Comment by arthurkiller** [comment]
> > @alexKeleon 你们对于使用 titan 有任何想交流和体验的也可以加微信群沟通~欢迎提出你们的想法和遇到的问题
> 
> 微信群怎么加

![IMG_4291](https://user-images.githubusercontent.com/11133870/140697730-8e9cd858-40c3-4fe5-952d-ddb939656840.PNG)
