### ISSUE TITLE
unknown command 'hello' in lettuce-core

### ISSUE THREAD

**Issue by wiltonlazary** [distributedio/titan#228]
unknown command 'hello', working different from official redis:

client: https://github.com/lettuce-io/lettuce-core

**Comment by arthurkiller** [comment]
hi @wiltonlazary, titan only supported the `RESP2` protocol currently, and the `hello` command is not implemented yet, you can check the full list of the commands `titan` supported from [here](https://github.com/distributedio/titan/blob/master/docs/command_list.md).

BTW, if you have any idea about the Redis new protocol, you can put up an issue freely.
