### ISSUE TITLE
set/zset proposal needed

### ISSUE THREAD

**Issue by yangmls** [distributedio/titan#39]
it's better to have a proposal for set/zset design, we can discuss here before implementing

**Comment by shafreeck** [comment]
The feature of `SET` is going to be done. The design is simple and we do not supply a proposal.

`ZSET` has not been started, and this should have a proposal first. Would you like to submit a proposal? You can write your proposal under [titan/proposals](https://github.com/meitu/titan/tree/master/proposals) directory and send a PR. It is not necessary a complete guide, it is just a start of discussion. And the proposal will be merge after improved as a complete guide.

**Comment by shafreeck** [comment]
# SET
Proposal: #44 
Codes: #45

**Comment by shafreeck** [comment]
All proposals required has been supplied in https://github.com/meitu/titan/tree/master/proposals
