### ISSUE TITLE
考虑支持tikv 3.0 titan 存储？

### ISSUE THREAD

**Issue by melin** [distributedio/titan#49]
考虑支持tikv 3.0 titan 存储？

**Comment by shafreeck** [comment]
我们会跟进Titan存储引擎的，不过主分支还是以稳定版tikv为准

**Comment by arthurkiller** [comment]
@shafreeck seems can be closed

**Comment by shafreeck** [comment]
TiKV SDK 已经更新到 v3.0.8，支持 Titan 引擎。
