### ISSUE TITLE
批量导入数，类似生成tikv 文件再load

### ISSUE THREAD

**Issue by melin** [distributedio/titan#75]
pingcap 数据同步工具lightning 有把数据直接生成 tikv/rocksdb的数据文件的代码，可以剥离出来。
再load 生成的文件，亿级别的数据量，insert 效率太慢

**Comment by YIDWang** [comment]
Thank you for your suggestion, which we will consider and support. Of course we are more welcome, you provide this pr

**Comment by YIDWang** [comment]
Thank you for your suggestion, which we will consider and support. Of course, you are more welcome to provide this pr

**Comment by YIDWang** [comment]
#

**Comment by YIDWang** [comment]
Thank you for your suggestion, which we will consider and support. Of course, you are more welcome to provide this pr

**Comment by shafreeck** [comment]
很好的建议，我们会考虑加入后续开发计划

**Comment by nioshield** [comment]
[titan-lightning](https://github.com/distributedio/titan-lightning)
这个工具已经能够支持这个功能
