### ISSUE TITLE
Aggressive all the elements of a complex data structure in one region as can as possible

### ISSUE THREAD

**Issue by shafreeck** [distributedio/titan#82]
This can improve performance to commit to one region instead of multiple regions.

According to the transaction model of TiKV, if the data being committed distributed in multiple regions, the `metakey` and `datakey` will be separated and the `metakey` will be committed as the secondary lock synchronized witch may cause lock-resolve when commits in the pipeline mode.

RFC is required to explain this issue and its solution.

**Comment by shafreeck** [comment]
## The key format now

```
MetaKey: {namespace}:{dbid}:M:{key}
DataKey: {namespace}:{dbid}:D:{objectid}
```

## Improvement

### Have a common prefix
```
MetaKey: {namespace}:{dbid}:{key}:M
DataKey: {namespace}:{dbid}:{key}:D:{objectid}
```

### Metakey is less than DataKey, so the MetaKey whould be the primary key when commiting the transaction in TiKV
```
MetaKey: {namespace}:{dbid}:{key}
Datakey: {namespace}:{dbid}:{key}:D:{objectid}
```

**Comment by shafreeck** [comment]
This feature is not necessary if we do not update the meta-information after updating the complex structure(list/set...).

**Comment by shafreeck** [comment]
After #85, the `UpdateAt` and `Len` is not necessary to maintain, so there is no need to update the meta-key every time.

However, there is an exception. When setting a key with expiration time, the meta-key must be updated.

**Comment by arthurkiller** [comment]
This is a breaking update and not a downward compatibility feature.

Maybe we should think about how to migrate data to the new format or compatible with the old format.

**Comment by shafreeck** [comment]
Compatibility should not be the barrier before 1.0. We indeed should consider compatibility because there are some production users, however, I prefer a `ops` way, not a `dev` way. For example, after 1.0, the data format could be changed and the original user who wants to upgrade to the latest version should migrate the data from the old cluster to a new one. I know it is painful, however, I think it is necessary to improve the `titan` project without too many history debts.

**Comment by arthurkiller** [comment]
agreed

**Comment by shafreeck** [comment]
Perhaps we could add the version to the key format, like:
```
{namespace}:{dbid}:{version}:M:{key}
```

**Comment by shafreeck** [comment]
Some ideas about this proposal:

* Ambiguity can not be avoided if the `MetaKey` and the `Datakey` share a common prefix because the generated key and the user key are in the same searching space.  A users always can construct a key the same as a generated key.

* 1PC still can be used if #85 is supported.

* When set expiration of a key, 2PC is unavoidable because the expiration list should be updated which mostly locates in another region.

* It is hard to keep compatibility with the original key format.
